let identity = system('git config user.identity | tr -d "\n"')

let g:user42 = 'angsanch'
let g:mail42 = 'angsanch@student.42madrid.com'

syntax on
set autoindent "mantain indentation level for next line
set number "add line numbers
set mouse=a

set tabstop=4 "Size of tabs

if identity == "epitech"
	set shiftwidth=4 "Autoindent size
	set expandtab "place spaces no tabs
    set softtabstop=4 "group delete spaces in tabs
endif

if identity == "epitech" || identity == "42"
    command Cc set colorcolumn=80
    command Ncc set colorcolumn-=80
    Cc
endif

" Highlight trailing spaces and tabs
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
