let identity = system('git config user.identity | tr -d "\n"')

let g:user42 = 'angsanch'
let g:mail42 = 'angsanch@student.42madrid.com'

syntax on
set autoindent "mantain indentation level for next line
set number "add line numbers
set mouse=a

set tabstop=4 "Size of tabs

if identity == "epitech"
	set shiftwidth=4 "Autoindent size
	set expandtab "place spaces no tabs
    set softtabstop=4 "group delete spaces in tabs
endif

let max_line_length = -1
if identity == "epitech"
	let max_line_length = 80
endif
if identity == "42"
	let max_line_length = 81
endif
if max_line_length != -1
	command! Cc execute 'set colorcolumn=' . max_line_length
   	command! Ncc execute 'set colorcolumn-=' . max_line_length
	Cc
endif

" Highlight trailing spaces and tabs
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
